language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly

branches:
  only:
    - master

before_install:
  - unset DYLD_LIBRARY_PATH
  - if [ `uname` == "Linux" ]; then
      unset DY_LIBRARY_PATH;
      bash ci/setup_travis_linux.sh;
      export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH";
    fi
  - if [ `uname` == "Darwin" ]; then
      sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4";
    fi
  - brew --config;
  - brew update;
  - if [ `uname` = "Linux" ]; then brew tap linuxbrew/xorg; fi
  - if [ `uname` == "Darwin" ]; then brew cask uninstall oclint; fi
  - brew tap dpo/openblas;
  - brew install mumps;
  - if [ `uname` == "Darwin" ]; then export TMPDIR=/tmp; fi  # for OpenMPI
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

install:
  - if [ `uname` == "Linux" ]; then
      julia -E 'using Libdl; push!(DL_LOAD_PATH, "/home/linuxbrew/.linuxbrew/lib"); using Pkg; Pkg.clone(pwd()); Pkg.build("MUMPS")';
    else
      julia -E 'using Pkg; Pkg.clone(pwd()); Pkg.build("MUMPS")';
    fi

script:
  - julia --check-bounds=yes -E 'using Pkg; Pkg.test("MUMPS"; coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("MUMPS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
